### ISSUE TITLE
Feedback for Milestone 2

### ISSUE THREAD

**Issue by arthursunbao** [UBC-MDS/kmeans_py#39]
Hi All,

Here is my comments based on milestone 2:

1. Please improve your style in Python programming, you can refer to https://google.github.io/styleguide/pyguide.html because the space you have between lines are not equal.

2. For your first line of your python file, it is suggested that you can include #!/usr/bin/env python just in case the user is running your code in Linux(like me)

3. I like your comments for the three functions, which are very well detailed explained. For the algorithm=‘kmenas++’, I would suggest you do not use ‘++’ as your input parameter char as in some special circumstances like regex lookup, it may cause trouble

4. For initialize_centers, where is your return value except for the line 129 “return None?”

5. For cluster_points, you said inputs are data, centers, max_iter,, but in your line 131 define cluster_points, you only have max_iter as default input parameter. I know you have __init__() which defines all the common shared variables, but this causes reviewer trouble reviewing your code

6. For cluster_points, I don’t see the output except for “return None”.  I am guessing that you are assuming these three functions are reading global variable they can share so that they don’t need to output result? This is not a good programming practice

7. Line 154: if not isinstance(self.K, int),  so what if K is negative? int also includes negative number. Please do defensive programming

8. Same question for report(), no input parameter?

Regards
Jason

**Comment by bradleypick** [comment]
2, 3, and 7 have been addressed. 

4,5, and 6 are not clear to us - there aren't global variables floating arounnd, the methods are referencing class attributes. We decided on the explicit `return None` to signify that the methods are called for their side effects. 

Closing to get another green badge!

**Comment by arthursunbao** [comment]
For 4, 5, 6, It is not a good practice to reference class attributes without specifically pointing out the return value of a function in the class. I would suggest you can return the class attributes in your function except from returning none.
