### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by arthursunbao** [UBC-MDS/kmeans_py#5]
Hi All,

Congrats for your work and you did a good job for finding a series of functions to develop. I have some suggestions regarding your current proposal:

1. It would be better if you can specify and encouraged to think in advance for the detailed data type of input parameters for each function, the data type of output value of the function, any side-corner cases you need to consider when doing unit tests to exclude, how much big(o) notation of computational complexity the function would have? These are all important aspects when you design a thoughtful function.

2. I suggest to name the function more discretely as kmeans++ seems to be not a good name for a function.

3. How will you package integrates and simplifies the Sklearn and Scipy's Kmeans? Please elaborate into details 

4. Where is the License file in your repo?

Regards
Jason

**Comment by bradleypick** [comment]
Most of this has been addressed in the v2.0 and v3.0 releases.
